# Numpy

Dans ce notebook, nous allons utiliser numpy et les array afin de gérer des sructures à plusieurs dimensions ne contenant qu'un seul type

In [1]:
import numpy as np

In [2]:
arr1=np.array([3,6,9,3],dtype=float)

In [3]:
arr1

array([ 3.,  6.,  9.,  3.])

In [4]:
print(arr1.size,arr1.ndim,arr1.shape)

4 1 (4,)


Générez des arrays remplis de 0 et de 1 de taille 10.


In [5]:
arr2=np.ones(10)

In [6]:
arr2

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [7]:
arr3=np.zeros((10,10))

In [8]:
arr3.shape

(10, 10)

In [9]:
arr4=np.ones(10)

In [10]:
arr4

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

On génère des array de suite de valeurs

In [11]:
arr5=np.linspace(0,5,11)

In [12]:
arr6=np.arange(0,5.5,0.5)

In [13]:
arr6==arr5

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True], dtype=bool)

Créez un array bidimensionnel avec des valeurs quelconques, calculer le cube de cet array


In [14]:
arr7=np.array([[2,4,6],[3,6,9]])

In [15]:
arr7.shape

(2, 3)

In [16]:
arr8=np.arange(1,10).reshape(3,3)

In [17]:
arr8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr8**3

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [19]:
arr9=np.array([5])

In [20]:
arr9

array([5])

In [21]:
arr9*arr8

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Générer un array avec des valeurs entre 0 et 8, afficher les éléments 1 à 6 puis modifiez les élément 6 à 8 en leur fixant la valeur de 22.


In [22]:
arr10=np.arange(9)

In [23]:
print(arr10[1:7])
arr10[-3:]=22

[1 2 3 4 5 6]


In [24]:
#pour éviter que arr10 soit impacté par une modif de arr11, on utilise 
#la méthode .copy()
arr11=arr10.copy()

In [25]:
arr11[-1]=33

In [26]:
arr10

array([ 0,  1,  2,  3,  4,  5, 22, 22, 22])

In [27]:
arr8[1,2]

6

### Produit matriciel

In [28]:
# on génère un array de taille 100000 x 100 rempli de nombres aléatoires
arr12=np.random.randn(10000000).reshape(100000,100)

arr12^T*arr12

In [29]:
%time arr13=np.dot(arr12.T,arr12)

Wall time: 48 ms


In [30]:
arr13.shape

(100, 100)

Générer un array de nombres aléatoires puis remplacer les valeurs plus petites que 0 par 0. Trier l’array obtenu


In [31]:
arr14=np.random.randn(100000,10)

In [32]:
#on calcule sa moyenne par colonne
arr14.mean(axis=0)

array([ 0.00308514, -0.00072062, -0.00145101, -0.00011381,  0.0005085 ,
        0.0016977 ,  0.00026227, -0.00512214,  0.00542661,  0.00206572])

In [33]:
#on calcul sa variance par colonne
arr14.var(axis=0)

array([ 1.00102168,  0.99485836,  1.00134076,  0.99661282,  0.9976714 ,
        0.99788037,  1.00531371,  0.99908655,  1.00161056,  1.00314925])

In [34]:
arr15=np.sort(np.where(arr14<0,0,arr14),axis=0)

In [35]:
print(arr15.mean(axis=0),arr15.var(axis=0))

[ 0.40067583  0.39761499  0.39904941  0.39825572  0.39831192  0.39937066
  0.40016597  0.39573499  0.40227696  0.40056018] [ 0.342348    0.33853821  0.33890645  0.33962045  0.341674    0.34104383
  0.34263056  0.33850168  0.34515077  0.34217695]


#### Sauvegarder des arrays

In [37]:
%time arr16=np.random.randn(1000000,100)

Wall time: 3.13 s


In [38]:
%time np.save("mon_array",arr16)

Wall time: 3.8 s


In [39]:
del arr16

In [40]:
%time arr16=np.load("mon_array.npy")

Wall time: 366 ms


In [41]:
arr16.shape

(1000000, 100)

In [42]:
%time arr17=np.random.randn(100000,100)

Wall time: 310 ms


In [43]:
%time np.savetxt("mon_array",arr17)

Wall time: 9.86 s


In [44]:
del arr17

In [45]:
%time arr17=np.loadtxt("mon_array")

Wall time: 14.4 s
